//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARCENTER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int ID_Factura { get; set; }
        public int Doc_Cliente { get; set; }
        public int Doc_Mecanico { get; set; }
        public int ID_Repuesto { get; set; }
        public int ID_Servicio { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Mecanico Mecanico { get; set; }
        public virtual Repuesto Repuesto { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
