//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARCENTER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public Servicio()
        {
            this.Factura = new HashSet<Factura>();
        }
    
        public int ID_Servicio { get; set; }
        public string Nombre { get; set; }
        public double Precio { get; set; }
    
        public virtual ICollection<Factura> Factura { get; set; }
    }
}
